### PR TITLE
Added 'herb' and 'US/UN' acronym support.

### PR DESCRIPTION
**Pull request by ojak**
This patch addresses issue https://github.com/rossmeissl/indefinite_article/issues/7

Version bumped.

### CODE REVIEW

**Comment by rossmeissl** [comment]
Hi @ojak, I don't think this quite works. I think it would produce "a usher" for example, which should be "an usher."

**Comment by rossmeissl** [comment]
@ojak in fact I think there's a better conversation going on this here https://github.com/rossmeissl/indefinite_article/pull/3

**Comment by anitagraham** [comment]
So only 8 years late here, but the pronunciation of 'herb' is different in different En variations.
I know Americans drop the 'h', but English and Australians pronounce it.

**Comment by rossmeissl** [comment]
Hi @anitagraham thanks! — are you interested in submitting a PR?

**Pull request closed without merging**
